[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Iota", email = "enoua5@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rnmmp-server[rns]",
]

[project.scripts]
server = "server:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
rnmmp-server = { path = "../../../packages/rnmmp-server" }
